//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourses {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibraryLanguage.App_GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abierto.
        /// </summary>
        public static string Abierto {
            get {
                return ResourceManager.GetString("Abierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceder.
        /// </summary>
        public static string Acceder {
            get {
                return ResourceManager.GetString("Acceder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña..
        /// </summary>
        public static string Cambiarpassword {
            get {
                return ResourceManager.GetString("Cambiarpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña..
        /// </summary>
        public static string confirmarpassword {
            get {
                return ResourceManager.GetString("confirmarpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico..
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digite un correo electrónico valido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo correo electrónico es obligatorio..
        /// </summary>
        public static string EmailRequerido {
            get {
                return ResourceManager.GetString("EmailRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Contraseña..
        /// </summary>
        public static string EnviarPassword {
            get {
                return ResourceManager.GetString("EnviarPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión..
        /// </summary>
        public static string iniciarsesion {
            get {
                return ResourceManager.GetString("iniciarsesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca su dirección de correo electrónico y se enviaran las instrucciones de recuperacion a se correo electrónico..
        /// </summary>
        public static string MensajeRecuperarCuenta {
            get {
                return ResourceManager.GetString("MensajeRecuperarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Nombres {
            get {
                return ResourceManager.GetString("Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvido su contraseña?.
        /// </summary>
        public static string Olvidepassword {
            get {
                return ResourceManager.GetString("Olvidepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña..
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo contraseña es obligatorio..
        /// </summary>
        public static string passwordRequerido {
            get {
                return ResourceManager.GetString("passwordRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Recordarme?.
        /// </summary>
        public static string Recordarme {
            get {
                return ResourceManager.GetString("Recordarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recupere su cuenta..
        /// </summary>
        public static string RecuperarCuenta {
            get {
                return ResourceManager.GetString("RecuperarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        public static string Registrarme {
            get {
                return ResourceManager.GetString("Registrarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo confirmar contraseña es obligatorio..
        /// </summary>
        public static string validacionconfirmarpassword {
            get {
                return ResourceManager.GetString("validacionconfirmarpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La {0} debe tener por lo menos {2} caracteres de longitud..
        /// </summary>
        public static string validacionlongitudcontraseña {
            get {
                return ResourceManager.GetString("validacionlongitudcontraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo nombres es obligatorio..
        /// </summary>
        public static string validacionnombres {
            get {
                return ResourceManager.GetString("validacionnombres", resourceCulture);
            }
        }
    }
}
